// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework;

#nullable disable

namespace TNC.Trading.Platform.Infrastructure.Infrastructure.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260921141001_DiagnoseCatalogModel")]
    partial class DiagnoseCatalogModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountDetailsAccountEntity", b =>
                {
                    b.Property<Guid>("AccountDetailsAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountAlias")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("AccountDetailsRetrievalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("Available")
                        .HasPrecision(19, 5)
                        .HasColumnType("decimal(19,5)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(19, 5)
                        .HasColumnType("decimal(19,5)");

                    b.Property<bool>("CanTransferFrom")
                        .HasColumnType("bit");

                    b.Property<bool>("CanTransferTo")
                        .HasColumnType("bit");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Deposit")
                        .HasPrecision(19, 5)
                        .HasColumnType("decimal(19,5)");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.Property<decimal>("ProfitLoss")
                        .HasPrecision(19, 5)
                        .HasColumnType("decimal(19,5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("AccountDetailsAccountId");

                    b.HasIndex("AccountDetailsRetrievalId", "AccountId")
                        .IsUnique();

                    b.ToTable("AccountDetailsAccounts");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountDetailsRetrievalEntity", b =>
                {
                    b.Property<Guid>("AccountDetailsRetrievalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountCount")
                        .HasColumnType("int");

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("TradingDay")
                        .HasColumnType("date");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AccountDetailsRetrievalId");

                    b.HasIndex("BrokerEnvironment", "TradingDay")
                        .IsUnique()
                        .HasFilter("[TriggerSource] = 'Automatic'");

                    b.HasIndex("BrokerEnvironment", "RetrievedAtUtc", "AccountDetailsRetrievalId");

                    b.HasIndex("BrokerEnvironmentId", "RetrievedAtUtc", "AccountDetailsRetrievalId");

                    b.ToTable("AccountDetailsRetrievals");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountPreferencesCurrentStateEntity", b =>
                {
                    b.Property<Guid>("AccountPreferencesCurrentStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AttemptId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthenticationSnapshotId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DesiredActor")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("DesiredChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("DesiredRevision")
                        .HasColumnType("bigint");

                    b.Property<bool?>("DesiredTrailingStopsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("FailureSummary")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("LastVerifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ObservedAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("ObservedTrailingStopsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PlatformEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("AccountPreferencesCurrentStateId");

                    b.HasIndex("BrokerEnvironmentId");

                    b.HasIndex("PlatformEnvironment", "BrokerEnvironment", "AccountId")
                        .IsUnique()
                        .HasFilter("[AccountId] IS NOT NULL");

                    b.HasIndex("PlatformEnvironment", "BrokerEnvironmentId", "AccountId")
                        .IsUnique()
                        .HasFilter("[BrokerEnvironmentId] IS NOT NULL");

                    b.ToTable("AccountPreferencesCurrentStates");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountPreferencesDesiredStateAuditEntity", b =>
                {
                    b.Property<Guid>("AccountPreferencesDesiredStateAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("AccountPreferencesCurrentStateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("NewRevision")
                        .HasColumnType("bigint");

                    b.Property<bool>("NewValue")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlatformEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("PreviousRevision")
                        .HasColumnType("bigint");

                    b.Property<bool?>("PreviousValue")
                        .HasColumnType("bit");

                    b.HasKey("AccountPreferencesDesiredStateAuditId");

                    b.HasIndex("BrokerEnvironmentId");

                    b.HasIndex("AccountPreferencesCurrentStateId", "NewRevision")
                        .IsUnique();

                    b.HasIndex("PlatformEnvironment", "BrokerEnvironment", "AccountId", "NewRevision");

                    b.HasIndex("PlatformEnvironment", "BrokerEnvironmentId", "AccountId", "NewRevision");

                    b.ToTable("AccountPreferencesDesiredStateAudits");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountPreferencesOperationEntity", b =>
                {
                    b.Property<Guid>("AccountPreferencesOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("BaselineRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PlatformEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("RequestedTrailingStopsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AccountPreferencesOperationId");

                    b.HasIndex("BrokerEnvironmentId");

                    b.HasIndex("PlatformEnvironment", "BrokerEnvironment", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PlatformEnvironment", "BrokerEnvironmentId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[BrokerEnvironmentId] IS NOT NULL");

                    b.ToTable("AccountPreferencesOperations");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AuthRetryCycleEntity", b =>
                {
                    b.Property<Guid>("RetryCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AutomaticAttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CycleType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("FailureNotificationSent")
                        .HasColumnType("bit");

                    b.Property<int?>("LastDelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("MaxAutomaticRetries")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PeriodicDelayMinutes")
                        .HasColumnType("int");

                    b.Property<string>("PlatformEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("RetryLimitReached")
                        .HasColumnType("bit");

                    b.Property<string>("RetryPhase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RetryCycleId");

                    b.HasIndex("BrokerEnvironmentId");

                    b.ToTable("AuthRetryCycles");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AuthRuntimeStateEntity", b =>
                {
                    b.Property<int>("AuthRuntimeStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthRuntimeStateId"));

                    b.Property<int>("AutomaticAttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentRetryCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EstablishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDegraded")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSuccessfulLoginAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastTransitionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastValidatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LatestFailureSummary")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("LatestIgLoginSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlatformEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("RetryLimitReached")
                        .HasColumnType("bit");

                    b.Property<string>("RetryPhase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TradingScheduleStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("AuthRuntimeStateId");

                    b.HasIndex("BrokerEnvironmentId");

                    b.ToTable("AuthRuntimeStates");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentDefaultsEntity", b =>
                {
                    b.Property<Guid>("BrokerEnvironmentDefaultsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankHolidayExclusionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationEmailTo")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("NotificationProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("RetryInitialDelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("RetryMaxAutomaticRetries")
                        .HasColumnType("int");

                    b.Property<int>("RetryMaxDelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("RetryMultiplier")
                        .HasColumnType("int");

                    b.Property<int>("RetryPeriodicDelayMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TradingDaysCsv")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<TimeOnly>("TradingHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TradingHoursStart")
                        .HasColumnType("time");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WeekendBehavior")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("BrokerEnvironmentDefaultsId");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("BrokerEnvironmentDefaults");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", b =>
                {
                    b.Property<Guid>("BrokerEnvironmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AvailabilityReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EndpointProfile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BrokerEnvironmentId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("BrokerEnvironments");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentNotificationProfileEntity", b =>
                {
                    b.Property<Guid>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultsVersion")
                        .HasColumnType("int");

                    b.Property<string>("EmailTo")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("BrokerEnvironmentId");

                    b.ToTable("BrokerEnvironmentNotificationProfiles");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentRetryProfileEntity", b =>
                {
                    b.Property<Guid>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultsVersion")
                        .HasColumnType("int");

                    b.Property<int>("InitialDelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("MaxAutomaticRetries")
                        .HasColumnType("int");

                    b.Property<int>("MaxDelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("Multiplier")
                        .HasColumnType("int");

                    b.Property<int>("PeriodicDelayMinutes")
                        .HasColumnType("int");

                    b.HasKey("BrokerEnvironmentId");

                    b.ToTable("BrokerEnvironmentRetryProfiles");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentScheduleProfileEntity", b =>
                {
                    b.Property<Guid>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankHolidayExclusionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultsVersion")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TradingDaysCsv")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<TimeOnly>("TradingHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TradingHoursStart")
                        .HasColumnType("time");

                    b.Property<string>("WeekendBehavior")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("BrokerEnvironmentId");

                    b.ToTable("BrokerEnvironmentScheduleProfiles");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentSelectionEntity", b =>
                {
                    b.Property<int>("SelectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SelectionId"));

                    b.Property<Guid?>("AppliedBrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RestartRequired")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SelectedBrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("SelectionId");

                    b.HasIndex("AppliedBrokerEnvironmentId");

                    b.HasIndex("SelectedBrokerEnvironmentId");

                    b.HasIndex("SelectionId")
                        .IsUnique();

                    b.ToTable("BrokerEnvironmentSelections");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.ConfigurationAuditEntity", b =>
                {
                    b.Property<long>("ConfigurationAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConfigurationAuditId"));

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlatformEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("ConfigurationAuditId");

                    b.ToTable("ConfigurationAudits");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.IgLoginSnapshotEntity", b =>
                {
                    b.Property<Guid>("IgLoginSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LightstreamerEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RawNonSecretPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseHeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("SessionExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SnapshotKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly>("TradingDay")
                        .HasColumnType("date");

                    b.HasKey("IgLoginSnapshotId");

                    b.HasIndex("BrokerEnvironment", "SnapshotKind", "TradingDay");

                    b.HasIndex("BrokerEnvironmentId", "SnapshotKind", "TradingDay");

                    b.ToTable("IgLoginSnapshots");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.IgProofDataEntity", b =>
                {
                    b.Property<int>("IgProofDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IgProofDataId"));

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OpenPositionCount")
                        .HasColumnType("int");

                    b.Property<string>("PreferredAccountId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PreferredAccountName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("IgProofDataId");

                    b.HasIndex("BrokerEnvironment")
                        .IsUnique();

                    b.HasIndex("BrokerEnvironmentId")
                        .IsUnique()
                        .HasFilter("[BrokerEnvironmentId] IS NOT NULL");

                    b.ToTable("IgProofData");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.NotificationRecordEntity", b =>
                {
                    b.Property<long>("NotificationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationRecordId"));

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DispatchStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PlatformEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid?>("RetryCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("NotificationRecordId");

                    b.ToTable("NotificationRecords");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.OperationalEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlatformEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("RetryCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("EventId");

                    b.ToTable("OperationalEvents");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.PlatformConfigurationEntity", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigurationId"));

                    b.Property<string>("BankHolidayExclusionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NotificationEmailTo")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("NotificationProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PlatformEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("RestartRequired")
                        .HasColumnType("bit");

                    b.Property<int>("RetryInitialDelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("RetryMaxAutomaticRetries")
                        .HasColumnType("int");

                    b.Property<int>("RetryMaxDelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("RetryMultiplier")
                        .HasColumnType("int");

                    b.Property<int>("RetryPeriodicDelayMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TradingDaysCsv")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<TimeOnly>("TradingHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TradingHoursStart")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeekendBehavior")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ConfigurationId");

                    b.ToTable("PlatformConfigurations");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.ProtectedCredentialEntity", b =>
                {
                    b.Property<int>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CredentialId"));

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtectionKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CredentialId");

                    b.HasIndex("BrokerEnvironment", "CredentialType")
                        .IsUnique();

                    b.HasIndex("BrokerEnvironmentId", "CredentialType")
                        .IsUnique()
                        .HasFilter("[BrokerEnvironmentId] IS NOT NULL");

                    b.ToTable("ProtectedCredentials");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.TrailingStopsPreferenceObservationEntity", b =>
                {
                    b.Property<Guid>("TrailingStopsPreferenceObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Actor")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BrokerEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("BrokerEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ObservationKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PlatformEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("TrailingStopsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("TrailingStopsPreferenceObservationId");

                    b.HasIndex("BrokerEnvironment", "PlatformEnvironment", "ObservedAtUtc", "TrailingStopsPreferenceObservationId");

                    b.HasIndex("BrokerEnvironmentId", "PlatformEnvironment", "ObservedAtUtc", "TrailingStopsPreferenceObservationId");

                    b.ToTable("TrailingStopsPreferenceObservations");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountDetailsAccountEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountDetailsRetrievalEntity", "Retrieval")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountDetailsRetrievalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Retrieval");
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountDetailsRetrievalEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountPreferencesCurrentStateEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountPreferencesDesiredStateAuditEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountPreferencesOperationEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AuthRetryCycleEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AuthRuntimeStateEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentNotificationProfileEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentRetryProfileEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentScheduleProfileEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentSelectionEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("AppliedBrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("SelectedBrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.IgLoginSnapshotEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.IgProofDataEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.ProtectedCredentialEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.TrailingStopsPreferenceObservationEntity", b =>
                {
                    b.HasOne("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.BrokerEnvironmentEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TNC.Trading.Platform.Infrastructure.Persistence.EntityFramework.Entities.AccountDetailsRetrievalEntity", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
